[versions]
encoding = "1.2.3"
bignum = "0.3.9"
vcLib = "3.7.0"
kmpCrypto = "3.1.0"
ida = "3.4.0"
eupid = "2.0.1"
atomicfu = "0.23.2"


[libraries]
base16 = { group = "io.matthewnelson.kotlin-components", name = "encoding-base16", version.ref = "encoding" }
base64 = { group = "io.matthewnelson.kotlin-components", name = "encoding-base64", version.ref = "encoding" }
bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "bignum" }
vclib = { group = "at.asitplus.wallet", name = "vclib", version.ref = "vcLib" }
kmpCrypto = { group = "at.asitplus.crypto", name = "datatypes", version.ref = "kmpCrypto" }
kmpCrypto-jws = { group = "at.asitplus.crypto", name = "datatypes-jws", version.ref = "kmpCrypto" }
kmpCrypto-cose = { group = "at.asitplus.crypto", name = "datatypes-cose", version.ref = "kmpCrypto" }
credential-ida = { module = "at.asitplus.wallet:idacredential", version.ref = "ida" }
credential-eupid = { module = "at.asitplus.wallet:eupidcredential", version.ref = "eupid" }
atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "atomicfu" }
vclib-openid = { group = "at.asitplus.wallet", name = "vclib-openid", version.ref = "vcLib" }

