name: iOS cache workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache@v4
        env:
          cache-name: cache-gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: iOS-${{ hashFiles('./gradle/libs.versions.toml', './gradle.properties') }}
      - name: Run shared tests
        run: ./gradlew :shared:iosSimulatorArm64Test
